REAL_MODE_STAGE_TWO:

	call CHECK_GRAPHICS_SUPPORT
	cmp ax, 0
	jl $
	
	call CLEAR_SCREEN
	
	call SET_MEMORY_MAP
	cmp ax, 0 
	jl $ ;memory map not set
	
	call ENABLE_A20_LINE_MAIN
	
	call GET_KERNEL_ELF_FILE_LOGICAL_SECTOR_NUMBER
	cmp ax, 0
	jl $
	mov [KERNEL_ELF_FILE_LOGICAL_SECTOR_NUMBER], al
	
	call LOAD_KERNEL_ELF_FILE_SEGMENTS
	cmp ax, 0
	jl $
	
	lgdt [GLOBAL_DESCRIPTOR_TABLE_DESCRIPTOR]
	mov eax, cr0
	or al, 1
	mov cr0, eax	
	
	jmp GLOBAL_DESCRIPTOR_TABLE_CODE_SEGMENT_DESCRIPTOR - GLOBAL_DESCRIPTOR_TABLE_START:PROTECTED_MODE_STAGE_ONE
