#ifndef MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_INC_CONSTANTS_H
#define MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_INC_CONSTANTS_H

#define COLOURED_TELETYPE_VIDEO_MODE_CONTENT_MEMORY_ADDRESS 0xB8000
#define SPACE_CHARACTER_ASCII_CODE 0x20
#define STANDARD_OUT_COLOUR_CODE 0x7

#endif /* !MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_INC_CONSTANTS_H */