#ifndef MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_INC_STRING_H
#define MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_INC_STRING_H

uint32_t get_string_length(char* string);

#endif /* !MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_INC_STRING_H */