#ifndef MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_GRAPHICS_DISPLAY_H
#define MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_GRAPHICS_DISPLAY_H

void print_line(char * message);

#endif /* !MARK_MUWONGE_EXPERIMENTAL_OS_KERNEL_GRAPHICS_DISPLAY_H */